language: cpp
compiler:
  - gcc
#  - clang

branches:
  only:
    - master
    - coverity_scan

notifications:
  email:
    recipients:
      - boinc_cvs@ssl.berkeley.edu
    on_success: always
    on_failure: always

# This switches to the container-based infrastructure and allows caching
sudo: false

cache:
  apt: true
  directories:
  - build/wxWidgets-3.0.2

addons:
  coverity_scan:
    project:
      name: "BOINC/boinc"
      description: "Build submitted via Travis CI"
    notification_email: christian.beer@posteo.de
    build_command_prepend: "./configure --enable-apps"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  apt_packages:
    - freeglut3-dev
    - libxmu-dev
    - libxi-dev
    #- python-mysqldb
    - libfcgi-dev
    #- libcurl4-openssl-dev
    #- libxss-dev
    - libnotify-dev
    - libxcb-util0-dev
    - libsqlite3-dev
    - libgtk2.0-dev
    - libwebkitgtk-dev

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Rd++Hyurnwd/tvjH0PX2seO3QUZ6WOf8bSB2ZkKPfZCU6+tXVMvloyog6Mlc7vl0m3WFAzw24MDtNLFBUktRsVXOkqDup1s6PdkwwcwG+5wAnydN+kXF9PcqKyOi0xJvl48Wji+r92Y9SCLzPnQGjZg70xHET22bDZHt2FsjP80="
  matrix:
    - BOINC_TYPE=libs
    - BOINC_TYPE=server
    - BOINC_TYPE=client
    - BOINC_TYPE=apps
    - BOINC_TYPE=manager
    #- BOINC_TYPE=coverity

matrix:
  fast_finish: true

before_script:
- ./_autosetup

script:
- if [[ "${BOINC_TYPE}" == "libs" ]]; then ( ./configure --disable-server --disable-client --disable-manager && make ) fi
- if [[ "${BOINC_TYPE}" == "server" ]]; then ( ./configure --disable-client --disable-manager && make ) fi
- if [[ "${BOINC_TYPE}" == "client" ]]; then ( ./configure --disable-server --disable-manager && make ) fi
- if [[ "${BOINC_TYPE}" == "apps" ]]; then ( ./configure --enable-apps --disable-server --disable-client --disable-manager && make ) fi
- if [[ "${BOINC_TYPE}" == "manager" ]]; then ( ./build/getWxWidgets.sh && ./configure --disable-server --disable-client --with-wxdir=./build/wxWidgets-3.0.2/buildgtk && make ) fi
